---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: localhost
  
  kafka-source:
    image: confluentinc/cp-enterprise-kafka:5.5.0
    hostname: kafka-source
    container_name: kafka-source
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka-source
      KAFKA_LISTENERS: PLAINTEXT://kafka-source:19091, EXTERNAL://kafka-source:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-source:19091, EXTERNAL://localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka-source
      KAFKA_BROKER_RACK: 0
    ports:
      - 9091:9091
  
  kafka-target:
    image: confluentinc/cp-enterprise-kafka:5.5.0
    hostname: kafka-target
    container_name: kafka-target
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka-target
      KAFKA_LISTENERS: PLAINTEXT://kafka-target:19092, EXTERNAL://kafka-target:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-target:19092, EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka-target
      KAFKA_BROKER_RACK: 0
    ports:
      - 9092:9092
  
  schema-registry-source:
    image: confluentinc/cp-schema-registry:5.5.0
    hostname: schema-registry-source
    container_name: schema-registry-source
    depends_on:
      - kafka-source
      - kafka-target
      
    ports:
      - "8091:8091"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-source
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-source:19091
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8091"
  
  
  schema-registry2:
    image: confluentinc/cp-schema-registry:5.5.0
    hostname: schema-registry2
    container_name: schema-registry2
    depends_on:
      - kafka-source
      - kafka-target
      - schema-registry-source
    ports:
      - "8092:8092"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry2
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-target:19092
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8092"
  
